[package]
name = "tauri-executor"
version = "0.1.0"
description = "Tauri Executor"
authors = ["Seu Nome"]
edition = "2021"

[dependencies]
tauri = { version = "1", features = ["api-all"] }

[build-dependencies]
tauri-build = "1"

[[bin]]
name = "tauri-executor"
path = "src-tauri/main.rs"
