[package]

name = "Tauri_Executor"

version = "0.1.0"

authors = ["Jrizz"]

edition = "2024"



[dependencies]

tauri = { version = "1.4", features = ["api-all"] }

libloading = "0.7"



[build-dependencies]



[features]

default = []
