name: Build Tauri Windows App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          override: true

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          npm install -g @tauri-apps/cli

      - name: Install Tauri prerequisites (webview2)
        run: |
          Invoke-WebRequest https://go.microsoft.com/fwlink/p/?LinkId=2124703 -OutFile MicrosoftEdgeWebView2Setup.exe
          Start-Process MicrosoftEdgeWebView2Setup.exe -ArgumentList "/install", "/silent", "/norestart" -NoNewWindow -Wait
        shell: pwsh

      - name: Build Tauri app
        run: npm run tauri:build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-windows-exe
          path: src-tauri/target/release/bundle
